import type { Metadata } from "next";
import "./globals.css";
import { SUIT } from "@/styles/fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased w-full h-screen max-h-screen`}>
        {children}
      </body>
    </html>
  );
}
