import type { Metadata } from "next";
import "./globals.css";
import { TanstackQueryClientProvider } from "@/providers/tanstackProviders";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased w-full h-screen max-h-screen mx-auto max-w-[500px] text-black p-4`}
      >
        <TanstackQueryClientProvider>{children}</TanstackQueryClientProvider>
      </body>
    </html>
  );
}
